### PR TITLE
#24 and #40 Testing

### PR DESCRIPTION
**Pull request by Ideawin**
#24 #40 Draft use cases tables for Functional Requirements Section 3.1

### CODE REVIEW

**Comment by dtopaloglou** [comment]
@claudds Please review. If all is okay, close issue #40.

**Comment by claudds** [comment]
@Ideawin These are good so far from what i see! there's a lot of info missing, these are still in progress right?

**Comment by Ideawin** [comment]
Yep, these aren't complete. I wanted to experiment with the commit/push :P I got the tables ready

**Comment by claudds** [comment]
@Ideawin ok perfect! They look great! I'm gonna leave this pull request open for now, so if you keep pushing to the same branch it should update this pull request :) when all your info is done, i'll merge it!

**Pull request merged**
