### PR TITLE
Deliverable 4 - Correction: Subsystems Interfaces Specs

### PR DESCRIPTION
**Pull request by limphilip**
#137 Removed _SavedUsers_ class and related methods.

Moved methods implemented by _Prerequisites_ class to _Course_ class, and removed _Prerequisites_ class.

### CODE REVIEW

**Comment by claudds** [comment]
@limphilip looks good so far! I'll leave this open in case we decide to scope out any of the requirements and it needs to be updated again!

**Comment by limphilip** [comment]
@claudds Good idea! I think I'll need to add the methods from the new use cases related to "manage users" into it.

**Comment by claudds** [comment]
@limphilip and also the other user cases for the admin functions which we will be creating! :)

**Comment by claudds** [comment]
@limphilip please do not wait for all of the dynamic design scenarios pertaining to admin use cases to be up, as we will not be drawing all of them! All of the ones we will be drawing are up (check my pull request for deliverable 4). Any other methods that you think may be needed but are not shown, feel free to make them up! :)

**Comment by limphilip** [comment]
@claudds Alright thanks! working on it right now :) Also, I originally changed the file directly from Deliverable 2 folder, do you want me to create a new one in Deliverable 4? If so I'll create a new pull request.

**Comment by claudds** [comment]
@limphilip if you coul, please move it to the deliverable 4 folder, that would be easier for me to keep track of what I'm putting into the final document :)

**Pull request closed without merging**
