### PR TITLE
#72 Deliverable 2 Section 3.2: Subsystems Interfaces Specification

### PR DESCRIPTION
**Pull request by limphilip**
#72 I accidentally deleted my branch that contains the file and it deleted the previous pull request x_x ... Here's a new one.

As previously discussed, I have now updated the return value of SavedSchedules to be Schedule or list of Schedule objects (depending on the method). Also, the HashMap return values have been changed to be "list of ... objects".

It is not finished yet, do not merge.

### CODE REVIEW

**Comment by claudds** [comment]
@limphilip since the teacher specified that he wants a student class (in place of the UI) maybe we should have another subsystem dealing with just the functions pertaining to student information? and this subsystem would interact with all of the other subsystems?

**Comment by limphilip** [comment]
@claudds Sure! So many of the functions currently on UI would be moved to Student? Will there still be a UI class at all in the specs after?

Also, I have put some other comments on the margin of the document, I'll put them here later when I get on a computer. There are basically a few things I am not sure about, mainly the way to specify a time block (start time, end time objects? or int? or a timeID corresponding to a block), and few method names could possibly changed to match an existing one, so that there would be only one method specification implemented by two classes.

**Comment by claudds** [comment]
@limphilip yes, exactly! I'm just going to change my diagrams by changing UI to student, so the subsystems would basically reflect that! And then there would just be a user subsystem to manage info like userID and stuff (for login/logout)

And yes, I was thinking of that too, at first i had thought int as start and end times maybe? And yes definitely, avoiding repetition in method names is definitely possible!! I'll look those over :)

**Comment by limphilip** [comment]
@claudds Thanks! I did some updates. I still need to update the names in the specifications according to your updated sequence diagram and the specs of Ryan's diagrams afterwards.

**Comment by limphilip** [comment]
**Update**
I have added most of the remaining methods from Ryan's sequence diagrams
I also reorganized the interfaces. There are now 5 interfaces, and a class will only be implementing methods for one interface. Consequently the tables have been simplified.

**Problems/Questions**
@RyanL94 @claudds 

**_(1)_** I cannot seem to find the sequence diagram (not SSD) for the login of a student, do I assume it is the same principle as the login SD for the admin?

**_(2)_** There are two methods which, I think, perform the same operations, but have different names:
gatherCoursesPassed(studentID:long) from View Academic Record
coursesPassed(studentID:long) from Generate Schedule

**_(3)_** Same as 2, for the following methods:
checkPrerequisites(courseID:long) from Generate Schedule
getPrerequisites() from Get Course Info
getPrerequisite(courseID:long) from Add Course

**Comment by claudds** [comment]
@limphilip  Great! Perfect that the interfaces have been scaled down and that you created new ones! As for your points: 

1) The contract Diagram for the Student Login is the contract right after Admin Login! But essentially yes, it's exactly the same as admin login, only it takes a studentID rather than an adminID.

2) Yes these are both basically the same methods! I'll try updating my diagrams to match ryans, since I already merged his request, but for the sake of the subsystems you can write them once (if they're both in the same class) and not worry about the naming in the diagrams too much! Same for 3), all 3 can be just one method :)

**Comment by limphilip** [comment]
Alright thanks! I will add the login for student shortly and choose one of the three for prerequisites :)

**Comment by limphilip** [comment]
@claudds Okay I updated and reviewed the document, I am unsure whether the methods generateSchedule and createSequence should really be implemented by the class Course though, or at least be found under the ICourseManagement interface. I can move them to their appropriate interfaces, but then the Course class would implement methods found in different interfaces. Looking at the past projects, I can't really find a team who did that... And if I change the class that implements them, it wouldn't match the sequence diagrams.

**Comment by claudds** [comment]
@limphilip I think it's fine to implement them in Course, because, the way I see it, there should be interaction between some of the subsystems (at least a little) and this is a perfect way to show that there is a little bit of interaction! :) I'll check out the document and merge it or let you know if there are any edits!

**Comment by claudds** [comment]
@limphilip everything looks okay, however I'm a little confused about one small thing. I see that there's methods implemented by SavedSchedule in two different interfaces - and that this is the only class that is implemented in two interfaces. Is this because it implements things provided by both interfaces?

**Comment by limphilip** [comment]
@claudds Thanks for the feedback! Are you referring to getAllSavedSchedules for example, that is in the IUserInteraction interface as well as the IScheduleManagement interface? If so, there are a few methods (addCourse, removeCourse for example) that can be called in the Student class as well as another class such as SavedSchedules or Course. But now that you mention it, it would maybe make more sense if I kept only the one that is really implementing it, and not just an override right? If that's the case I will remove a couple of methods from the IUserInteraction interface, possibly rename it and update the description that goes with that interface.

**Comment by claudds** [comment]
@limphilip yes that's exactly what I meant! I think maybe keeping it in the interface that implements it is a good idea! :)

**Comment by limphilip** [comment]
@claudds I changed it, all method overrides have been removed from IUserInterface, and kept only in the appropriate interface that really implements them.

**Comment by claudds** [comment]
@limphilip  Perfect! Great work!

**Pull request merged**
