### PR TITLE
#12 Intro is done. -Ryan Lee

### PR DESCRIPTION
**Pull request by RyanL94**
#12 @claudds Please review

### CODE REVIEW

**Comment by claudds** [comment]
@RyanL94 please replace "Specifications" with "Preferences", and the word students is missing near the end of the 1st paragraph :)

**Comment by dtopaloglou** [comment]
@RyanL94 Is this introduction to system?

**Comment by dtopaloglou** [comment]
I think it is by the looks of the pull request title. However, it's not showing in #12. You'll need to reference it in the comments section and not in the title...

**Comment by RyanL94** [comment]
@dtopaloglou fixed it

**Pull request merged**
