### PR TITLE
Deliverable 3 - Testing and Intro

### PR DESCRIPTION
**Pull request by RyanL94**
@claudds #125 and #122 as well as updated gantt chart ready for review

### CODE REVIEW

**Comment by claudds** [comment]
@RyanL94 everything is good so far! Just missing the user manual for both of your sections and this will be good to go

**Comment by RyanL94** [comment]
@claudds added user manual

**Comment by claudds** [comment]
@RyanL94 better! Just missing a few screenshots to make the user manual a little more professional! :)

**Comment by claudds** [comment]
@RyanL94 great stuff! Merging

**Pull request merged**
