### PR TITLE
Deliverable 3: Generate schedule + Manage Users

### PR DESCRIPTION
**Pull request by limphilip**
#125 #129 Pull request for generate schedule and manage users, will contain the users manual part and the testing.

Note: view weekly schedule has been removed (?)

### CODE REVIEW

**Comment by claudds** [comment]
@limphilip looks good so far! I'm not sure about the weekly view, but I believe @dtopaloglou had phased out this use case due to time constraints.

**Comment by limphilip** [comment]
@claudds Ok if it is scoped out should I still write tests for them and cross them out? The other parts are done:

_**Users Manual**_:
- Generate Schedule instructions is on the corresponding document, includes screenshots
- Manage users include: search/advanced search, view user, update user, delete user

_**Requirement Testing**_:
- Tests for _Generate Schedule_ 
- Tests for _Manage User_ (search/view user/update user/delete user)

_**Comments**_:
- Please let me know if you want me to change the figure numbers, same for the section in the users' manual
- I updated the 'manage users' use cases for #140 so that there is only one use case for _Search_ and _Advanced Search_, the use case associated to requirement testing for _Search_ have therefore been updated

@SOEN341-W16/coding I am not sure whether the following is a normal behavior:
(1) As an administrator, go to manage users page
(2) Click on update on a user
(3) Do not touch anything, and hit save
(4) The password of this user will have changed

**Comment by claudds** [comment]
@limphilip no, if we scope out a functionality, no test cases are required! :) we'll mention the scoped out things in the untested list! Also, don't worry about figure numbers, I'll keep those updated myself once I put the whole document together! :) 

edit: I was wrong! Please write the test cases for the scoped out functions and simply strike through the entire table!

**Comment by claudds** [comment]
@limphilip Everything looks great! Test cases and user manual are perfect!! Just missing the scoped out test case, and we're good to merge!

**Comment by limphilip** [comment]
@claudds Okay! I added the scoped out test cases.

**Comment by claudds** [comment]
@limphilip all good! merging!

**Pull request merged**
