### PR TITLE
Deliverable 4 - Revisions

### PR DESCRIPTION
**Pull request by AlineTheAlien**
#141 #142 #144 #155

Final revisions for Deliverable 4

### CODE REVIEW

**Comment by AlineTheAlien** [comment]
@claudds Should we also remove the SavedSchedules class from the project? It seems redundant just like the SavedUsers class

**Comment by claudds** [comment]
@AlineTheAlien I would leave it in for now, we could ask in the tutorial this week!

**Comment by claudds** [comment]
@AlineTheAlien everything looks good! Merging!

**Comment by AlineTheAlien** [comment]
@claudds Waiiit I wasn't done LOL I still had domain model to modify :O

**Comment by AlineTheAlien** [comment]
@claudds I'll make a new pull request hahaha

**Comment by claudds** [comment]
@AlineTheAlien SHOOT! lol sorry!!!!

**Comment by AlineTheAlien** [comment]
@claudds Dw about it :dancer:

**Pull request merged**
