### PR TITLE
Daniel

### PR DESCRIPTION
**Pull request by ddicorpo**
#17 #22 Added 6.1 and 7.3

### CODE REVIEW

**Comment by claudds** [comment]
@ddicorpo Perfect! Estimation is great! For architecture, could you maybe also elaborate how the framework makes it easier to work with this model, and how this model is best for web-based systems in general? Just to make the paragraphs a little longer and have a more thorough explanation

**Comment by dtopaloglou** [comment]
@ddicorpo For the MVC model, take a look to what I wrote in "Technologies Used" section.

**Comment by ddicorpo** [comment]
Made the changes to architecture, let me know if it's ok

**Comment by claudds** [comment]
@ddicorpo it's perfect!  I'll merge when I get on the computer since it says the branch has conflicts for some reason

**Pull request merged**
