### PR TITLE
#18 Activities table

### PR DESCRIPTION
**Pull request by limphilip**
#18 Activities & assignment table.

-How will members be assigned to future activities from deliverable 2 and 3?

### CODE REVIEW

**Comment by claudds** [comment]
@limphilip tables are perfect! Could you fill in the assigned persons section once your other section has been completed as well? :) 

I'm not entirely sure how we should assign parts. Maybe we can discuss this in the Doc team meeting this week @ddicorpo? I think we should assign entire teams to tasks instead of people for the sake of this document and then split up tasks on github when the time comes. What do you think?

**Comment by limphilip** [comment]
@claudds Should section 7.4 also have its own table for the assigned members for each activities? If it is case I will move the last column of this document to section 7.4; this one will not look so heavy.

**Comment by claudds** [comment]
@limphilip Yes i think that would be a better solution! Good thinking!

**Comment by limphilip** [comment]
@claudds The column with assigned members have been removed. I will create another pull request for issue #20 (Activities Assignments), which will contain a document with another separate table.

**Comment by claudds** [comment]
@limphilip perfect! Thank you!

**Pull request merged**
