### PR TITLE
Deliverable 3 - Testing & User Manual (Browse Course List + Add Course + Add User)

### PR DESCRIPTION
**Pull request by Ideawin**
#125 #129 Browse Course List and Add Course not implemented yet, so I just made two small test tables so I can modify them later if the functionalities are added.

For Add User, I made a test case + new use case

### CODE REVIEW

**Comment by claudds** [comment]
@Ideawin looking good so far! For the functionalities that haven't been implemented yet, please don't strike them out as we aren't sure if they will be scoped out yet (only if time is too constrained). If/when they are, then we will strike them out! :)

**Comment by dtopaloglou** [comment]
@Ideawin @claudds Browse course list for users has been added FYI.

**Comment by claudds** [comment]
@Ideawin also, for the use case 16, could you please remove that from this doc and add it to a pull request for deliverable 4, referencing issue #155 :) just for organization

**Comment by Ideawin** [comment]
Alright will do!

On Sun, Apr 3, 2016 at 3:39 PM, Claudia Della Serra <
notifications@github.com> wrote:

> @Ideawin https://github.com/Ideawin also, for the use case 16, could
> you please remove that from this doc and add it to a pull request for
> deliverable 4, referencing issue #155
> https://github.com/SOEN341-W16/ConUScheduler/issues/155 :) just for
> organization
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/SOEN341-W16/ConUScheduler/pull/150#issuecomment-205040897

## 

Ideawin-B. Koun

**Comment by claudds** [comment]
@Ideawin almost ready to merge! Just missing the user manual for browse course list and you'll be good to go

**Comment by claudds** [comment]
@Ideawin perfect! Merging

**Pull request merged**
