### PR TITLE
Deliverable 3 - Testing & User Manual

### PR DESCRIPTION
**Pull request by AlineTheAlien**
#125 #129 New use case for Manage Courses (administrator)

### CODE REVIEW

**Comment by claudds** [comment]
@AlineTheAlien just checked this out! Looks good, but in the basic flow, there should be communication between the system and the admin, like admin requests to manage a course, and in the next step the system sends back a list of all the courses to manage, or something like that!

**Comment by AlineTheAlien** [comment]
@claudds I know coding isn't final yet but I scoped out view sequence for now, if you have time can you review my stuff for del3? :)

**Comment by claudds** [comment]
@AlineTheAlien test cases and user manual are PERFECT!!! Love it! Can you please remove the use case from this pull request tho, before i merge? It should go in a deliverable 4 pull request (referencing issue #155). Also, for that use case, could you please divide all functionalities for managing courses into different use cases (one function per use case)!

**Comment by AlineTheAlien** [comment]
@claudds thanks gurl :+1: I removed the manage courses use case, I'll make those changes for del4!

**Comment by claudds** [comment]
@AlineTheAlien Perfect!!! Merging!

**Pull request merged**
