### PR TITLE
#25 Completed a portion of the Constraints and Qualities of sec 3.3

### PR DESCRIPTION
**Pull request by dtopaloglou**
#25 @claudds Make sure to check the contents :+1:

### CODE REVIEW

**Comment by claudds** [comment]
@dtopaloglou Would interoperability fall under the cross-browser compatibility point? They sound like extensions of the same point, maybe you could merge them into 2 paragraphs under the same subheading?

**Comment by ddicorpo** [comment]
@dtopaloglou You should merge interoperability and cross-browser compatibility, like @claudds mentioned and you could call it just "Cross Browser Compability". 

you could say, "By having multiple browsers to code for, layout and functionality may alter depending on which browser the client is using". Or something along those lines

**Comment by dtopaloglou** [comment]
@claudds @ddicorpo I'll fix.

**Comment by dtopaloglou** [comment]
@claudds @ddicorpo Please review.

**Pull request merged**
