### PR TITLE
Began consolodating parts for final version of Deliverable 1

### PR DESCRIPTION
**Pull request by claudds**
#28 began merging all completed parts into one final version. Added formatting and layout design. Please do not close until version is complete!

### CODE REVIEW

**Comment by dtopaloglou** [comment]
@claudds Make sure to add headers that auto-index so that they can be accessed via a table of Contents. A good example is the Nexus project found in Moodle; you'll see what I'm talking about.

**Comment by claudds** [comment]
@dtopaloglou Ah yeah I saw it! Sure, I could do a table of contents for Deliverable 1! Also, are we going to get it printed and bound?

**Comment by dtopaloglou** [comment]
@claudds I guess we could :smile: it'll look nice.

**Comment by claudds** [comment]
@dtopaloglou sounds good! :)

**Comment by claudds** [comment]
@dtopaloglou @ddicorpo Deliverable 1 is finished! Please review ASAP so that it can be submitted for printing :)

**Pull request merged**
