### PR TITLE
#77 Updated Rapid Prototyping

### PR DESCRIPTION
**Pull request by Ideawin**
Not completed yet, do not close. There are some parts I can't screenshot yet, but I'll do it soon after the coding team finish what they planned to do this weekend. Also, I'm not sure how specific the screenshots should be!

### CODE REVIEW

**Comment by claudds** [comment]
@Ideawin the mock ups are actually perfect this way! I don't think we'll need anymore, just an explanation of the courses and users manager mock up should be enough, and maybe a little elaboration on the risk (if you can find anything else to talk about) and it'll be ready to merge!! :)

**Comment by Ideawin** [comment]
@claudds Alright, I will add more text to this. :)

**Comment by Ideawin** [comment]
I updated it again, let me know if there is something to modify~

**Comment by claudds** [comment]
@Ideawin great work! Merging!

**Pull request merged**
