### PR TITLE
#72 Deliverable 2 Section 3.2: Subsystems Interfaces Specification

### PR DESCRIPTION
**Pull request by limphilip**
#72 The specifications of the the IUserInterface have been added. The return type of each method should be confirmed. Specification for other interfaces still need to be completed.

### CODE REVIEW

**Comment by limphilip** [comment]
Do not merge yet please, it is not completed.

**Comment by claudds** [comment]
@limphilip looking good so far! For the hashmap return values, maybe @dtopaloglou should review. As for the SavedSchedules return value, maybe have that as a Schedule return value instead, as it would return a list of Schedule objects (or a single Schedule object)!

**Comment by dtopaloglou** [comment]
@limphilip @claudds There are no return types in PHP; in fact they're called 'mixed'. PHP can return any value, including fully constructed arrays. If we're talking about HashMaps or eveb Lists, it is equivalent to a multi-dimensional, associative array.

**Comment by claudds** [comment]
@dtopaloglou so then, we could say the return type would be an array of the class type that the method would be returning? so, for example, Schedule[]?

**Comment by limphilip** [comment]
Thanks for the feedback @claudds & @dtopaloglou ! 

I will make the changes for SavedSchedules return value.

As for the HashMap, I think Dimitri is right about the associative array, I basically wanted a key-value form for the return type, which would represent the "courseInfo" and "courseInfoAndSections" return messages from the sequence diagrams. Is there a formal way to represent an associative array in PHP? All I can find is "array()".

I think an array of the class type can work in this case, but I think it would require a full in-depth copy of each course returned since we do not want the caller to be able to modify the courses, just to consult some info about them. It would however be more descriptive then "array()".

**Comment by limphilip** [comment]
Oh well, looking at the past projects, it doesn't seem to be implementation-specific, nor extremely formal. It looks like the specifications in SOEN 331, instead of using notations like [] for arrays or any group of elements, they use list<expectedType>, which leaves the implementation team to decide which type of list (array, linked list, hashmap, etc.) to use. Recall in the assignment 2 of SOEN 331, they use "sequence of ..." instead of list<>. Would that be a good idea? It shows what's expected from the method, but doesn't show how it is implemented.

**Comment by claudds** [comment]
@limphilip that's actually a perfect idea. I just checked the past projects, and i found that they either use "list of ... objects" or just the ClassName[] format (check the Bacon & Cobalt projects), so whichever you feel comfortable with would work! Also, for the return value "courseInfoAndSections", i realize that that was a badly written return value by myself. It should just be an array of sections returned :) i'll change that up in the sequence diagrams!

**Pull request closed without merging**
