### PR TITLE
updated Gantt chart and some preliminary diagrams

### PR DESCRIPTION
**Pull request by RyanL94**
#75 #105  sequence and system sequence diagrams are done, to be improved, will do contracts separately

### CODE REVIEW

**Comment by claudds** [comment]
@RyanL94 OK so the gantt chart is great! The sequence diagrams have a few minor bugs to fix! 
1. Make sure all calls are in the form of function names (so no spaces & all have arguments if applicable)
2. There should be no "System" class, the student class should be making those calls directly to another class in the system. I guess for this to make sense, instead of having your actor call "message1" they should be calling the contract message, and then the student class should be calling all of the messages that you put on the system classes. Are these contract diagrams or your preliminary SSDs? 
3. Make sure to always be passing arguments to your classes. For example, in the create course sequence contract diagram, get preference list should be passing the studentID to the method, etc. 
4. Again, the course database shouldn't be there, just a straight access to the course class from the student class
5. Generator also shouldn't be a class (since it is literally only there to generate something, which the teacher said shouldn't happen), so you could have those methods be in the schedule class instead :) 

Let me know if those more complex diagrams are contracts :)

**Comment by RyanL94** [comment]
#105 is complete

**Comment by RyanL94** [comment]
#75 is still incomplete, sorry. Right now it's ugly as all hell, but the diagrams themselves I believe are done. Contracts are all that remain, which will be updated in a few hours.

**Comment by claudds** [comment]
@RyanL94 Everything looks great! Just 2 small edits please: 
1. In the logout SSD for the admit, on one of the return values you have logon page, but for everything else you have logout page, please fix for consistency!
2. In your contract tables, please specify on the post conditions either attribute modification, instance deletion/creation, or association creation/deletion!

Gantt chart is good to go! I'll merge everything after these edits :)

**Comment by RyanL94** [comment]
#75 updated, ready for further review

**Comment by claudds** [comment]
@RyanL94 perfect! Merging! Great work! :)

**Pull request merged**
