### PR TITLE
issue #53,23,55

### PR DESCRIPTION
**Pull request by Malclir**
Added UCD1.jpeg (issue #55, #24 )
Added risk table to Risk document (issue #23 )
Fixed Login Logout Use case (issue #39 )

### CODE REVIEW

**Comment by claudds** [comment]
@MarcLeclair Ok, so everything looks great! Use cases and risk table are perfect! Only issue is with the UCD, there should only be 12 bubbles for the 12 Student Use Cases, and each bubble should have the same name as each of the use cases.  Also, I think change preferences should extend manually manipulate sequence. 

I think all of the Administrator use cases are fine, could you just change "class list" to "view class list" please :)

**Comment by Malclir** [comment]
Hum even though it was scoped out should I add teacher stuff too? Or more things in admin... I have some weird feelings that something is missing

**Comment by claudds** [comment]
@MarcLeclair Sure, you could add teacher stuff if you want! I think the teacher was just able to view or manage his own section tho

**Comment by Malclir** [comment]
@claudds  #63 I just changed (hopefully it worked) some stuff. I added a new link between scheduler and admin and student  with scheduler. I took the initiative to add the scheduler bubble because I felt like it was a crucial part of our system and that's how the admin can interact with the student part. I'll change if need be

**Comment by Malclir** [comment]
@claudds  issue #63 , changed log in ---> schedule into "log into scheduler"

**Pull request merged**
