### PR TITLE
#71 D2 Section 3.1 - Architecture - class diagram

### PR DESCRIPTION
**Pull request by AlineTheAlien**
#71 #73 Sorry about closing the other pull requests twice, had some problems with gitbash but everything should be ok now :) Please do not merge yet!

### CODE REVIEW

**Comment by claudds** [comment]
@AlineTheAlien so i just checked the diagram out and i have a few recommendations!
1. Student and Program Coordinator classes should be subclasses of User (or User could be an interface and Student and Program Coordinator would implement this interface)
2. The Course class should be an aggregation of Section objects
3. There should be a class called SavedSchedules, which is an aggregation of Schedule objects 
4. There should be associations between classes like in the Domain Model (although i think these are missing because your diagram isn't finished lol)
5. For the methods of the classes, you should get these from me & Ryan's sequence diagrams (or Philip's part). Also, in the sequence diagrams, the methods belong to the classes that the arrowhead points to 

Also, don't forget that there should be a description to go along with the diagram (like the way Nexus did, just describing the diagram and this view of the architecture)

**Comment by AlineTheAlien** [comment]
added @MarcLeclair 's use case diagram from deliverable 1 for the "+ 1" view of 4+1 architecture

**Comment by AlineTheAlien** [comment]
@claudds For my class diagram, looking at you and Ryan's sequence diagrams, are you sure the methods belong to the classes that the arrowheads point to? For example, where you have getAllSavedSchedules(studentID), there's a diagram where it points to System class, and another where it points to Student class. I would have that method in both classes then? Wouldn't it make sense that the methods belongs to the class that's invoking it?

**Comment by claudds** [comment]
@AlineTheAlien no no, there should be no System class! The system sequence diagrams just consider the system as a whole, the actual contract diagrams are what you should be looking at. Methods in those diagrams belong to the classes that the arrow heads are pointing to because those are the ones that are receiving the "messages" to run those methods :) so for your example, it would belong to the student class

**Comment by AlineTheAlien** [comment]
@claudds ohhh okay that clears up so much, thanks gurl ;D

**Comment by claudds** [comment]
@AlineTheAlien No Problem girl! :) also, my & Ryan's diagrams are a little uncoordinated in naming of methods, so it might be better to look at Philip's subsystems as well to get a good idea of the methods

**Comment by AlineTheAlien** [comment]
@claudds if you have time can you check over the logic view diagram here so I can do the subsystem diagrams? :)

**Comment by claudds** [comment]
@AlineTheAlien diagram is perfect! One small edit that should be done, however, is the arrows going to user from Student and Admin; their heads should be closed and empty (like empty triangles, in star, the arrow is called the "Generalization" association). Also, a small description for the use case diagram is needed!

**Comment by claudds** [comment]
@AlineTheAlien also, administrator should be implementing the methods addCourse and removeCourse, addUser and removeUser!

**Comment by AlineTheAlien** [comment]
@claudds You can review everything and let me know if anything needs changes! Merge the pull request whenever =)

**Comment by claudds** [comment]
@AlineTheAlien all good!

**Pull request merged**
